# 站点名称
site_name: 'LinuxGuide'
# 仓库链接
repo_url: https://github.com/ZJDoc/LinuxGuide
# 作者
site_author: 'zhujian'
# 版权信息
copyright: '2021, zhujian'
# 源文件目录
docs_dir: 'docs'
# 生成静态文件目录
site_dir: 'site'
# 额外信息
extra:
    # 版本号
    version: 0.1.0
# 主题
theme: 
    # name: 'readthedocs'
    # name: 'mkdocs'
    name: 'material'
# markdown扩展
markdown_extensions:
  # 参考[MathJax](https://squidfunk.github.io/mkdocs-material/reference/mathjax/)，支持数学公式渲染
  - pymdownx.arithmatex:
      generic: true
    # 参考[Icons + Emojis](https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/)，执行Markdown Emoji
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# mathjax
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# 导航
nav:
    - Home: index.md
    - 系统配置:
        - 更换国内源: configure/更换国内源.md
        - '[Ubuntu]DEBIAN_FRONTEND': configure/ubuntu-DEBIAN_FRONTEND.md
        - '[LOCALE]字符集设置': configure/locale-字符集设置.md
        - 扩展命令行窗口滚动行数: configure/扩展命令行窗口滚动行数.md
        - '[localtime]设置时区': configure/localtime-设置时区.md
        - '[Ubuntu]中文乱码': configure/ubuntu-中文乱码.md
        - 制作桌面启动器: configure/制作桌面启动器.md
        - '应用查询、安装、卸载和清理': configure/应用查询-安装-卸载-清理.md
        - '[apt]升级操作': configure/apt-升级操作.md
        - 查询阻塞进程并杀死: configure/查询阻塞进程并杀死.md
        - 删除陈旧的APT仓库: configure/删除陈旧的APT仓库.md
        - 系统备份: configure/系统备份.md
        - '[控制台窗口][快捷键]复制和粘贴': configure/快捷键-复制和粘贴.md
        - '[WPS]中文字体': configure/wps-中文字体.md

        - 'Ubuntu 16.04':
            - '[Thinkpad T470p]安装Ubuntu 16.04单系统及Nvidia显卡驱动安装': 'configure/[Thinkpad T470p]安装Ubuntu 16.04单系统及Nvidia显卡驱动安装.md'
            - '[Thinkpad T470p][Ubuntu 16.04]双显卡配置': 'configure/[Thinkpad T470p][Ubuntu 16.04]双显卡配置.md'
            - '[Ubuntu 16.04]Cuda和Cudnn安装': 'configure/[Ubuntu 16.04]Cuda和Cudnn安装.md'
            - '[Ubuntu 16.04]桌面美化': 'configure/[Ubuntu 16.04]桌面美化.md'
            - '[Ubuntu 16.04]VMware安装': 'configure/[Ubuntu 16.04]VMware安装.md'
            - '[Ubuntu 16.04]开放热点': 'configure/[Ubuntu 16.04]开放热点.md'
            - '[Ubuntu 16.04]Thunderbird邮箱配置': 'configure/[Ubuntu 16.04]Thunderbird邮箱配置.md'
        - 'Ubuntu 18.04':
            - '[Ubuntu 18.04]PPA方式安装Nvidia驱动': 'configure/[Ubuntu 18.04]PPA方式安装Nvidia驱动.md'
            - '[Ubuntu 18.04]桌面美化': 'configure/[Ubuntu 18.04]桌面美化.md'
            - '[Ubuntu 18.04]VMware安装': 'configure/[Ubuntu 18.04]VMware安装.md'
            - '[Docker][Ubuntu 18.04]g++安装失败': 'configure/[Docker][Ubuntu 18.04]g++安装失败.md'
        - 问题解答: configure/troubleshooting.md
    - 工具使用:
        - CMake: tool/cmake.md
        - Java: tool/java.md
        - 'Apache Ant': tool/apache-ant.md
        - '[Indicator Stickynotes]桌面便签': tool/indicator-stickynotes.md
        - '[grep]文本搜索': tool/grep.md
        - '[sed]文本替换': tool/sed.md
        - '[grep][sed]替换目录下所有符合条件的内容': tool/grep-sed.md
        - '[cp]复制目录下排除某个文件或文件夹外的所有文件': tool/cp.md
        - '[rsync]断点续传': tool/rsync.md
        - '[sshfs]挂载远程文件系统': tool/sshfs.md
        - '[tar]解压缩文件和目录': tool/tar.md
        - '[zip]解压缩文件和目录': tool/zip.md
        - '[7zip]解压缩文件和目录': tool/7zip.md
        - '[unrar]解压缩rar文件': tool/unrar.md
        - '[tee]数据写入和输出': tool/tee.md
        - '[split][cat]分块或合并大文件': tool/split-cat.md
        - '[alias]命令别名设置': tool/alias.md
        - '[ls][df][du]查看文件、目录、文件系统大小': tool/ls-df-du.md
        - '[touch][mkdir]创建文件、文件夹': tool/touch-mkdir.md
        - '[free]内存使用查询': tool/free.md
        - '[ln]软链接和硬链接': tool/ln.md
        - '[watch]命令监测': tool/watch.md
        - '[wget]文件下载': tool/wget.md
        - '[curl]网页调试': tool/curl.md
        - '[wc]统计目录中文件个数': tool/wc.md
        - '[eog]命令行图像查看工具': tool/eog.md
        - '[tmux]终端复用器': tool/tmux.md
        - '[aria2]下载工具': tool/aria2.md
        - '[thunar]文件管理器': tool/thunar.md
        - '[tabby]命令行终端': tool/tabby.md
    - 常用操作:
        - 格式化移动硬盘: operation/格式化移动硬盘.md
        - 复制大量小文件: operation/复制大量小文件.md
        - 对目录下的每一个文件夹单独打包: operation/对目录下的每一个文件夹单独打包.md
    - 访问控制:
        - 分区和文件系统: access/分区和文件系统.md
        - 文件权限: access/文件权限.md
        - 目录权限: access/目录权限.md
        - sudo使用: access/sudo使用.md
        - '用户查询、创建和删除': access/用户查询-创建和删除.md
        - 用户权限调整: access/用户权限调整.md
        - '组查询、创建和删除': access/组查询-创建和删除.md
        - 组权限调整: access/组权限调整.md
        - 本地用户信息: access/本地用户信息.md
        - 本地组信息: access/本地组信息.md
        - 用户密码: access/用户密码.md
    - 脚本语法:
        - 'dash vs. bash': shell/dash-bash.md
        - set: shell/set.md
        - 变量: shell/变量.md
        - 参数传递: shell/参数传递.md
        - 流程控制: shell/流程控制.md
        - 基本运算符: shell/基本运算符.md
        - 条件表达式: shell/条件表达式.md
        - 函数: shell/函数.md
        - 输入和输出重定向: shell/输入和输出重定向.md
        - 字符串: shell/字符串.md
        - 问题解答: shell/troubleshooting.md