# 站点名称
site_name: 'LinuxGuide'
# 仓库链接
repo_url: https://github.com/ZJDoc/LinuxGuide
# 作者
site_author: 'zhujian'
# 版权信息
copyright: '2021, zhujian'
# 源文件目录
docs_dir: 'docs'
# 生成静态文件目录
site_dir: 'site'
# 额外信息
extra:
    # 版本号
    version: 0.1.0
# 主题
theme: 
    # name: 'readthedocs'
    # name: 'mkdocs'
    name: 'material'
# markdown扩展
markdown_extensions:
  # 参考[MathJax](https://squidfunk.github.io/mkdocs-material/reference/mathjax/)，支持数学公式渲染
  - pymdownx.arithmatex:
      generic: true
    # 参考[Icons + Emojis](https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/)，执行Markdown Emoji
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# mathjax
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# 导航
nav:
    - Home: index.md
    - 访问控制:
        - 文件权限: access/文件权限.md
        - 目录权限: access/目录权限.md
        - sudo使用: access/sudo使用.md
        - '用户查询、创建和删除': access/用户查询-创建和删除.md
        - 用户权限调整: access/用户权限调整.md
        - '组查询、创建和删除': access/组查询-创建和删除.md
        - 组权限调整: access/组权限调整.md
        - 本地用户信息: access/本地用户信息.md
        - 本地组信息: access/本地组信息.md
        - 用户密码: access/用户密码.md
    - 脚本语法:
        - 'dash vs. bash': shell/dash-bash.md
        - set: shell/set.md
        - 变量: shell/变量.md
        - 参数传递: shell/参数传递.md
        - 流程控制: shell/流程控制.md
        - 基本运算符: shell/基本运算符.md
        - 条件表达式: shell/条件表达式.md
        - 函数: shell/函数.md
        - 输入和输出重定向: shell/输入和输出重定向.md
        - 字符串: shell/字符串.md
        - ERROR: shell/error.md